/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/login/login" |
       "/pages/index/index" |
       "/pages/forewarning/forewarning" |
       "/pages/maintenance/maintenance" |
       "/pages/personal/personal" |
       "/pages-sub/change-password/change-password" |
       "/pages-sub/shop/shop" |
       "/pages-sub/sign-in/sign-in" |
       "/pages-sub/knowledge/category/category" |
       "/pages-sub/knowledge/company/company" |
       "/pages-sub/knowledge/file/file" |
       "/pages-sub/lift/detail/detail" |
       "/pages-sub/lift/enter/enter" |
       "/pages-sub/lift/list/list" |
       "/pages-sub/lift/monitor/monitor";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/maintenance/maintenance" | "/pages/forewarning/forewarning" | "/pages/personal/personal"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
