/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/login/login" |
       "/pages/index/index" |
       "/pages/maintenance/maintenance" |
       "/pages/personal/personal" |
       "/pages/shop/shop" |
       "/pages/sign-in/sign-in" |
       "/pages/urgent-repair/urgent-repair copy" |
       "/pages/urgent-repair/urgent-repair" |
       "/pages/knowledge/category/category" |
       "/pages/knowledge/company/company" |
       "/pages/knowledge/file/file" |
       "/pages/lift/detail/detail" |
       "/pages/lift/enter/enter" |
       "/pages/lift/list/list" |
       "/pages/lift/monitor/monitor";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/maintenance/maintenance" | "/pages/urgent-repair/urgent-repair" | "/pages/personal/personal"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
