/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/login/login" |
       "/pages/index/index" |
       "/pages/add-elevator/add-elevator" |
       "/pages/elevator-detail/elevator-detail" |
       "/pages/elevator-list/elevator-list" |
       "/pages/knowledge-company/knowledge-company" |
       "/pages/knowledge-list/knowledge-list" |
       "/pages/maintenance/maintenance" |
       "/pages/personal/personal" |
       "/pages/shop/shop" |
       "/pages/urgent-repair/urgent-repair";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/maintenance/maintenance" | "/pages/urgent-repair/urgent-repair" | "/pages/personal/personal"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
